name: SpacemiT K3

on:
  push:
    paths:
      - '.github/workflows/spacemit-k3.yml'
      - 'spacemit/k3/**'

jobs:
  build-uboot:
    name: Build U-Boot for SpacemiT K3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ctx
      - name: Setup Toolchains
        id: setup-gcc-toolchain
        uses: ./ctx/.github/actions/gcc-riscv64-unknown-linux-gnu
      - name: Checkout U-Boot Source
        uses: actions/checkout@v5
        with:
          repository: openeuler-riscv/u-boot.git
          # branch spacemit-k3-vendor-2022.10 as of 20260907
          ref: cf395e05d4b6dc5641545c47b3afedf73254e092
          fetch-depth: 1
          path: u-boot
      - name: Build U-Boot
        # K3 doesn't have out-of-tree build support
        run: |
          make -C u-boot -j $(nproc) CROSS_COMPILE=${{ steps.setup-gcc-toolchain.outputs.full-prefix }} k3_oerv_defconfig
          make -C u-boot -j $(nproc) CROSS_COMPILE=${{ steps.setup-gcc-toolchain.outputs.full-prefix }}
      - name: Collect Results
        run: |
          mkdir dist
          cp u-boot/u-boot.itb dist
          cp u-boot/u-boot-env-default.bin dist
          cp u-boot/FSBL.bin dist
          cp u-boot/bootinfo_spinor.bin dist
          cp ./ctx/spacemit/k3/partition_4M.json dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: uboot
          path: dist

  build-opensbi:
    name: Build OpenSBI for SpacemiT K3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ctx
      - name: Setup Toolchains
        id: setup-gcc-toolchain
        uses: ./ctx/.github/actions/gcc-riscv64-unknown-linux-gnu
      - name: Checkout OpenSBI Source
        uses: actions/checkout@v5
        with:
          repository: bianbu-linux/opensbi.git
          github-server-url: https://gitee.com
          ref: k3-br-v1.0.7
          fetch-depth: 1
          path: opensbi
      - name: Build OpenSBI
        run: |
          make -C opensbi -j $(nproc) CROSS_COMPILE=${{ steps.setup-gcc-toolchain.outputs.full-prefix }} PLATFORM=generic PLATFORM_DEFCONFIG=k3_defconfig
      - name: Collect
        run: |
          mkdir dist
          cp opensbi/build/platform/generic/firmware/fw_dynamic.itb dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: opensbi
          path: dist

  build-esos:
    name: Build esos.itb for SpacemiT K3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ctx
      - name: Setup Toolchains
        id: setup-gcc-toolchain
        uses: ./ctx/.github/actions/gcc-riscv64-unknown-elf
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y scons lzop
      - name: Checkout esos Source
        uses: actions/checkout@v6
        with:
          repository: openeuler-riscv/spacemit-k3-firmware-esos.git
          # branch spacemit-k3-esos as of 20260904
          ref: 4005e21aaf2b45a29e6d5bc586fcd843593f928e
          fetch-depth: 1
          path: esos
      - name: Checkout esos-lite Source
        uses: actions/checkout@v6
        with:
          repository: openeuler-riscv/spacemit-k3-firmware-esos-lite.git
          # branch spacemit-k3-esos-lite as of 20260904
          ref: 0400dad1b722dd9c235852a27f6396cc8e83076a
          fetch-depth: 1
          path: esos/components/esos-lite
      - name: Build esos-lite
        working-directory: esos/components/esos-lite/rt-thread/bsp/spacemit
        run: |
          RTT_EXEC_PATH="${{ steps.setup-gcc-toolchain.outputs.path }}" scons
      - name: Build esos
        working-directory: esos/bsp/spacemit
        run: |
          RTT_EXEC_PATH="${{ steps.setup-gcc-toolchain.outputs.path }}" scons core0
          RTT_EXEC_PATH="${{ steps.setup-gcc-toolchain.outputs.path }}" scons core1
      - name: Build itb
        working-directory: esos
        run: |
          mkimage -f esos_rt24.its ../output/esos_rt24.itb
      - name: Collect
        run: |
          mkdir dist
          cp output/esos_rt24.itb dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: esos
          path: dist

  collect:
    name: Archiving Files
    needs:
      - build-uboot
      - build-opensbi
      - build-esos
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Artifacts
        uses: actions/download-artifact@v8
        with:
          run-id: ${{inputs.run_id}}
          merge-multiple: true
          path: staging
      - name: Archiving
        working-directory: staging
        run: |
          mkdir ../dist
          zip -r ../dist/bl-spacemit-k3.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: firmware
          path: dist

  release:
    name: Release Firmware for SpacemiT K3
    needs:
      - collect
    uses: ./.github/workflows/artifact-release.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      tag_name: release-spacemit-k3
      release_name: Boot Firmware for SpacemiT K3
      run_id: ${{github.run_id}}
      artifact_pattern: "firmware"
